version: '3.8'

services:
  bot:
    build: .
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - ADMIN_GROUP_ID=${ADMIN_GROUP_ID}
      - GROUP_ID_50_1=${GROUP_ID_50_1}  # ✅ Erste Gruppen-ID für 50€ Nutzer
      - GROUP_ID_50_2=${GROUP_ID_50_2}  # ✅ Zweite Gruppen-ID für 50€ Nutzer
      - GROUP_ID_25=${GROUP_ID_25}  # ✅ Gruppen-ID für 25€ Nutzer
      - GROUP_ID_100_1=${GROUP_ID_100_1}  # ✅ Erste Gruppen-ID für 100€ Nutzer
      - GROUP_ID_100_2=${GROUP_ID_100_2}  # ✅ Zweite Gruppen-ID für 100€ Nutzer
      - GROUP_ID_100_3=${GROUP_ID_100_3}  # ✅ Dritte Gruppen-ID für 100€ Nutzer
      - GROUP_ID_100_4=${GROUP_ID_100_4}  # ✅ Vierte Gruppen-ID für 100€ Nutzer
      - MONGODB_URI=${MONGODB_URI}
      - ADMIN_USERNAME=${ADMIN_USERNAME}
      - DB_HOST=db
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data: