version: '3.8'

services:
  bot:
    build: .
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - ADMIN_GROUP_ID=${ADMIN_GROUP_ID}
      - MONGODB_URI=${MONGODB_URI}
      - INVITED_GROUP_ID=${INVITED_GROUP_ID}
      - ADMIN_USERNAME=${ADMIN_USERNAME}
      - DB_HOST=db
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - GROUP_ID_100=${GROUP_ID_100}  # ✅ Gruppen-ID für 100€ Codes
      - GROUP_ID_50=${GROUP_ID_50}    # ✅ Gruppen-ID für 50€ Codes
      - GROUP_ID_25=${GROUP_ID_25}    # ✅ Gruppen-ID für 25€ Codes
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data: